/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wbq_meibaiimage_ndkimage_NdkImageUtils */

#ifndef _Included_com_wbq_meibaiimage_ndkimage_NdkImageUtils
#define _Included_com_wbq_meibaiimage_ndkimage_NdkImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wbq_meibaiimage_ndkimage_NdkImageUtils
 * Method:    getNdkImage
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_wbq_meibaiimage_ndkimage_NdkImageUtils_getNdkImage
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
